### ISSUE TITLE
HideMe8 Lite: Disable Screen Bounce

### ISSUE THREAD

**Issue by 23matt** [MohammadAG/iOS-DoubleTapToSleep#1]
Turning this "Disable Screen Bounde" on in HideMe8 Lite causes the doubletaptosleep to stop working while the iPhone is locked. Had this issue on iPhone 5, iOS 8.4.

**Comment by MohammadAG** [comment]
That's a HideMe8 bug, not DoubleTapToSleep.

Try this deb: https://drive.google.com/file/d/0BybKJwYV-sTfQjRpVDBaWW1LNzQ/view?usp=sharing and disable that option.

Point the dev to this, it's the source of that deb: https://gist.github.com/MohammadAG/0b7dbe7e27937d8fc6ad
